const softdrink=["pepsi","fanta","minrinda","coke","sprit","big cola","lacasera" ,
"bigg apple","maltina","beer","team","seven up"]
console.log(softdrink[2])
console.log(softdrink[3])
console.log(softdrink[4])
console.log(softdrink[1])
console.log(softdrink[5])
console.log(softdrink[6])
console.log(softdrink[7])
console.log(softdrink[8])
console.log(softdrink[10])
console.log(softdrink[9])
console.log(softdrink[11])
console.log(softdrink[13])
console.log(softdrink[12])
console.log(softdrink.length)
console.log(orangedrink)
console.log("Wecome")